#!/usr/bin/env bash
#
# Deploy MAIC (OpenMAIC) to the Aliyun lightweight server behind nginx.
#
# Run from the repository root in Git Bash:
#   bash .deploy/deploy-maic.sh
#
# What it does (image is built locally, the server never runs a heavy build):
#   1. Locally: `docker build` for linux/amd64 (idempotent, reuses layer cache).
#   2. Streams the image to the server over ssh (`docker save | gzip | docker load`)
#      so no intermediate file has to fit on either disk.
#   3. Recreates the app container on the maic-net network, next to the
#      `maic-postgres` database container.
#
# Secrets never appear on the command line: the runtime env file is generated by
# .deploy/make-env.mjs and uploaded separately (see --env-file below).
set -euo pipefail

SERVER="${MAIC_SERVER:-root@47.116.20.229}"
REMOTE_DIR="${MAIC_REMOTE_DIR:-/root/maic}"
IMAGE="${MAIC_IMAGE:-maic:local}"
CONTAINER="${MAIC_CONTAINER:-maic}"
PORT="${MAIC_PORT:-3000}"
SSH_OPTS=(-o BatchMode=yes -o StrictHostKeyChecking=no)

step() { printf '\n==> %s\n' "$1"; }

# ---------- 1. Build ----------
if [[ "${MAIC_SKIP_BUILD:-0}" != "1" ]]; then
  step "Building $IMAGE for linux/amd64"
  docker build --platform linux/amd64 \
    --build-arg NEXT_PUBLIC_PRO_WORKBENCH_ENABLED=true \
    -t "$IMAGE" .
fi

# The runtime env file must exist; it holds DATABASE_URL and the session secret.
if [[ ! -f /tmp/maic-app.env ]]; then
  echo "ERROR: /tmp/maic-app.env missing — run .deploy/make-env.mjs first." >&2
  exit 1
fi

# ---------- 2. Transfer image ----------
step "Streaming image to $SERVER"
# `gzip -1` is deliberate: the link is the bottleneck, not the CPU, and the image
# is already mostly incompressible layers.
docker save "$IMAGE" | gzip -1 | ssh "${SSH_OPTS[@]}" "$SERVER" 'gunzip | docker load'

# ---------- 3. Recreate container ----------
step "Recreating container $CONTAINER"
scp "${SSH_OPTS[@]}" /tmp/maic-app.env "$SERVER:$REMOTE_DIR/maic-app.env"

ssh "${SSH_OPTS[@]}" "$SERVER" bash -s <<REMOTE
set -e
chmod 600 $REMOTE_DIR/maic-app.env
mkdir -p $REMOTE_DIR/data
# The image runs as uid 1001 (nextjs); the data volume must be writable by it,
# otherwise the first write to /app/data fails.
chown 1001:1001 $REMOTE_DIR/data

docker rm -f $CONTAINER >/dev/null 2>&1 || true
docker run -d --name $CONTAINER --restart unless-stopped \\
  --network maic-net \\
  -p 127.0.0.1:$PORT:3000 \\
  -v $REMOTE_DIR/data:/app/data \\
  --env-file $REMOTE_DIR/maic-app.env \\
  $IMAGE
REMOTE

# ---------- 4. Wait for readiness ----------
step "Waiting for the app to answer on 127.0.0.1:$PORT"
# Cold start runs the schema bootstrap and seeds the first admin, so allow time.
health_code() {
  ssh "${SSH_OPTS[@]}" "$SERVER" "curl -s -o /dev/null -w '%{http_code}' --max-time 8 http://127.0.0.1:$PORT/api/health" 2>/dev/null || true
}
ready=0
for _ in $(seq 1 30); do
  if [[ "$(health_code)" == "200" ]]; then
    echo "App is up (HTTP 200)."
    ready=1
    break
  fi
  sleep 5
done
if [[ "$ready" != "1" ]]; then
  echo "WARNING: app did not return 200 within 150s — check the log tail below." >&2
fi

step "Container log tail"
ssh "${SSH_OPTS[@]}" "$SERVER" "docker logs --tail 25 $CONTAINER 2>&1 || true"

step "Done. Site: https://maic.omnisource.xin"
