#!/usr/bin/env node
/**
 * Build a Docker `--env-file` for the server from a local dotenv-style file.
 *
 * Why a generator instead of shipping `.env.local` as-is:
 *   1. dotenv (Next.js) strips surrounding quotes; `docker run --env-file` does
 *      NOT. Handing Docker `MODEL_ROUTES='{...}'` passes the quotes through and
 *      `JSON.parse` in `lib/server/config-validation.ts` then rejects the value.
 *   2. Docker env-file is last-write-wins for duplicates, matching dotenv, but
 *      emitting one line per key keeps the file readable and auditable.
 *   3. The runtime file needs deployment-specific keys (database URL, session
 *      secret, bootstrap password) that must not live in the repo.
 *
 * Usage:
 *   node .deploy/make-env.mjs --source .env.local --out /tmp/maic.env \
 *     --set DATABASE_URL=postgres://... --set TEACHER_SESSION_SECRET=...
 *
 * `--set` values win over anything read from the source file. Secrets are only
 * ever written to `--out`; nothing is printed.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import process from 'node:process';

/** Keys compiled into the browser bundle at build time — meaningless at runtime. */
const BUILD_ONLY_PREFIX = 'NEXT_PUBLIC_';

/** Parse KEY=VALUE, honouring quotes and inline `#` comments like dotenv does. */
function parseDotenv(text) {
  const entries = new Map();
  for (const rawLine of text.replace(/^\uFEFF/, '').split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) continue;
    let value = line.slice(eq + 1).trim();
    if (value.startsWith('"') || value.startsWith("'")) {
      // Quoted: take everything up to the matching closing quote (dotenv keeps
      // `#` inside quotes literal, so no inline-comment stripping here).
      const quote = value[0];
      const end = value.indexOf(quote, 1);
      value = end === -1 ? value.slice(1) : value.slice(1, end);
    } else {
      // Unquoted: an unescaped ` #` starts a comment.
      const hash = value.indexOf(' #');
      if (hash !== -1) value = value.slice(0, hash).trim();
    }
    // Last occurrence wins, matching dotenv's parse-then-assign behaviour.
    entries.set(key, value);
  }
  return entries;
}

/** Reject values Docker cannot represent in an env-file (newline/multiline). */
function assertRepresentable(key, value) {
  if (/[\r\n]/.test(value)) {
    throw new Error(`${key} contains a newline, which docker --env-file cannot represent`);
  }
}

function main() {
  const args = process.argv.slice(2);
  const options = { source: '.env.local', out: '/tmp/maic.env', sets: [] };
  for (let i = 0; i < args.length; i += 1) {
    const [flag, inline] = args[i].split('=');
    const value = inline ?? args[(i += 1)];
    if (flag === '--source') options.source = value;
    else if (flag === '--out') options.out = value;
    else if (flag === '--set') options.sets.push(value);
    else throw new Error(`Unknown argument: ${flag}`);
  }

  const entries = parseDotenv(readFileSync(options.source, 'utf8'));
  for (const pair of options.sets) {
    const eq = pair.indexOf('=');
    if (eq === -1) throw new Error(`--set expects KEY=VALUE, got: ${pair}`);
    entries.set(pair.slice(0, eq), pair.slice(eq + 1));
  }

  const lines = [];
  const skipped = [];
  for (const [key, value] of entries) {
    if (key.startsWith(BUILD_ONLY_PREFIX)) {
      skipped.push(key);
      continue;
    }
    assertRepresentable(key, value);
    // Empty values are intentionally kept: an explicit empty string differs
    // from "unset" for several flags in this codebase.
    lines.push(`${key}=${value}`);
  }

  const header = [
    '# Generated by .deploy/make-env.mjs — do not edit by hand.',
    `# Source: ${options.source}`,
    skipped.length
      ? `# Omitted build-time keys (baked into the image): ${skipped.join(', ')}`
      : '# No build-time keys present in the source.',
    '',
  ];
  writeFileSync(options.out, `${header.join('\n')}${lines.join('\n')}\n`, { mode: 0o600 });
  process.stdout.write(
    `Wrote ${lines.length} variables to ${options.out}` +
      (skipped.length ? ` (omitted ${skipped.length} NEXT_PUBLIC_* build-time keys).\n` : '.\n'),
  );
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    main();
  } catch (error) {
    process.stderr.write(`Failed: ${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  }
}
